### PR TITLE
Copy item details

### PR DESCRIPTION
**Pull request by phedlund**
Restores the functionality described in issue https://github.com/mronkko/ZotPad/issues/68.

### CODE REVIEW

**Comment by mronkko** [comment]
Unfortunately I cannot pull this change. I had not heard from this change for a while, so I implemented it myself by changing all the fields in the UIItemDetailView to UITextViews that support text selection and copying. This is included already in 1.2.1 version that is now in the App Store.

**Comment by phedlund** [comment]
OK, good. Can you push your latest code to GitHub?

**Comment by mronkko** [comment]
Hi

Pushed the 1.2 branch, which contains ZotPad 1.2.3 code.

I did not push the master, because it is seriously broken as I am currently refactoring it to support the new version of Zotero server.

If you have time and interest to do some coding, please let me know and I will check the tracker.

Mikko

On Mar 13, 2013, at 3:48 PM, Peter Hedlund <notifications@github.com<mailto:notifications@github.com>>
 wrote:

OK, good. Can you push your latest code to GitHub?

**Comment by mronkko** [comment]
Hi

I marked several issues with a new tag "Help needed". These are more or less local issues that would be easy to fix or implement.

https://github.com/mronkko/ZotPad/issues?labels=Help+needed&page=1&state=open

Mikko

On Mar 13, 2013, at 8:42 PM, Mikko Rönkkö <mikko.ronkko@aalto.fi<mailto:mikko.ronkko@aalto.fi>> wrote:

Hi

Pushed the 1.2 branch, which contains ZotPad 1.2.3 code.

I did not push the master, because it is seriously broken as I am currently refactoring it to support the new version of Zotero server.

If you have time and interest to do some coding, please let me know and I will check the tracker.

Mikko

On Mar 13, 2013, at 3:48 PM, Peter Hedlund <notifications@github.com<mailto:notifications@github.com>>
 wrote:

OK, good. Can you push your latest code to GitHub?

**Pull request closed without merging**
